#!/usr/bin/env bash

set -e

# You can change these to fit your configuration.
#
# Specify a modified CONFIG_DIR value to the dyndns_update script through an
# environment variable with the same name: `CONFIG_DIR=<my-value> dyndns_update`.
# Note: this is only necessary when you call `dyndns_update` manually.
CONFIG_DIR="/etc/ddns"
BIN_DIR="/usr/local/bin"

print_usage() {
    echo "Usage: deploy_client [--domain DOMAIN_NAME] [--stack-name CFN_STACK_NAME] [--secret SECRET] HOST"
    echo ""
    echo "Multiple DDNS clients for different domains can be deployed to the"
    echo "same machine by invoking this deployment script for each of them."
}

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]
do
    case $1 in
        --domain)
            DOMAIN_NAME="$2"
            shift
            shift
            ;;
        --stack-name)
            STACK_NAME="$2"
            shift
            shift
            ;;
        --secret)
            SECRET="$2"
            shift
            shift
            ;;
        -*|--*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            POSITIONAL_ARGS+=("$1")  # Save positional arg
            shift
            ;;
    esac
done

set -- "${POSITIONAL_ARGS[@]}"  # Restore positional arguments

# Process positional arguments
if [[ -z "$1" ]]; then
    print_usage
    exit 1
fi
host="$1"

# Process required option parameters
if [[ -z "$DOMAIN_NAME" ]]; then
    echo "Required option --domain not set. Exiting."
    exit 1
fi
if [[ -z "$STACK_NAME" ]]; then
    echo "Required option --stack-name not set. Exiting."
    exit 1
fi

# Perform some additional checks
if [[ ! -f ./get_dyndns_lambda_url ]]; then
    echo "Helper script ./get_dyndns_lambda_url not found." \
         "Are you in the same directory as the deploy_client script?"
    exit 1
fi
if [[ ! -f ./dyndns_update ]]; then
    echo "Helper script ./dyndns_update not found." \
         "Are you in the same directory as the deploy_client script?"
    exit 1
fi

# Don't change these.
secret_file="$CONFIG_DIR/$DOMAIN_NAME/shared_secret"
lambda_url_file="$CONFIG_DIR/$DOMAIN_NAME/lambda_url"
ddns_hostname_file="$CONFIG_DIR/$DOMAIN_NAME/ddns_hostname"

# Test connection
if ! ssh $host -T "echo 42"; then
    echo "Unable to connect to $host via SSH. Exiting."
    exit 1
fi

# Ensure that all required directories exist
ssh $host -T "mkdir -p $CONFIG_DIR/$DOMAIN_NAME"
ssh $host -T "mkdir -p $BIN_DIR"

# Process shared_secret settings
if [[ -z "$SECRET" ]] && ! ssh $host "test -e $secret_file"
then
    echo "The secret has not yet been configured for this client. Specify with --secret."
    exit 1
fi

if [[ -n "$SECRET" ]]
then
    echo $SECRET | ssh $host -T "cat > $secret_file"
    ssh $host -T "chmod 0600 $secret_file"
fi

# Configure domain name on the client
echo $DOMAIN_NAME | ssh $host -T "cat > $ddns_hostname_file"

# Query lambda URL
echo "Querying DDNS Lambda function URL..."
if ! lambda_url=$(./get_dyndns_lambda_url $STACK_NAME); then
    echo "Error when querying the DDNS Lambda function URL. Exiting."
    exit 1
fi
echo "Found! Configuring client to call $lambda_url..."
echo "$lambda_url" | ssh $host -T "cat > $lambda_url_file"

# Install binary and crontab entry
echo "Installing DDNS update script on the client..."
scp -q ./dyndns_update "$host:$BIN_DIR/"

echo "Creating crontab entry on the client (will log to /var/log/ddns_update.log)..."
cron_entry="*/20 * * * * CONFIG_DIR=$CONFIG_DIR /bin/bash $BIN_DIR/dyndns_update >> /var/log/ddns_update.log"
if ! ssh $host -T "crontab -l | grep 'dyndns_update' 1>/dev/null"; then
    ssh $host -T "(crontab -l ; echo '$cron_entry') | crontab -"
else
    echo "Crontab entry already exists. Skipping."
fi

# Perform initial ddns update
echo "Performing initial DDNS update on the client..."
ssh $host -T "CONFIG_DIR=$CONFIG_DIR /bin/bash $BIN_DIR/dyndns_update"
