#!/usr/bin/env bash

if [[ -z "$CONFIG_DIR" ]]; then
    CONFIG_DIR="/etc/ddns"
fi

expect_file () {
    if [[ ! -f $1 ]]
    then
        echo "Expected configuration file $1 to exist. Exiting."
        exit 1
    fi
}

expect_file "$CONFIG_DIR/shared_secret"
expect_file "$CONFIG_DIR/lambda_url"
expect_file "$CONFIG_DIR/ddns_hostname"

url=$(cat "$CONFIG_DIR/lambda_url")
host=$(cat "$CONFIG_DIR/ddns_hostname")
secret=$(cat "$CONFIG_DIR/shared_secret")

ip=$(curl --ipv4 -q -s -X POST \
    -H 'content-type: application/json' \
    -d '{"execution_mode": "get"}' \
    $url \
    | python -c 'import json, sys; print(json.load(sys.stdin)["return_message"])')
echo "My IP: $ip"

# Post DDNS request
hash=$(echo -n "$ip$host$secret" | sha256sum | awk '{print $1}')
curl --ipv4 -q -s -X POST \
    -H 'content-type: application/json' \
    -d '{"execution_mode":"set", "validation_hash":"'$hash'","ddns_hostname":"'$host'"}' $url
echo ""
